#!/bin/bash
#Gets needed file from github
git clone https://github.com/JakeRoggenbuck/ConfigFiles ~/Downloads/ConfigFiles
git clone https://github.com/JakeRoggenbuck/.scripts.git ~/.scripts 

#Removes and adds dirs
rm -ri ~/Desktop

mv ~/Templates ~/.templates

mkdir ~/Repos
mkdir ~/Resources

mkdir ~/Media

mv ~/Pictures ~/Media
mv ~/Music ~/Media
mv ~/Videos ~/Media

#Moves needed config files
cd ~/Downloads/ConfigFiles
mv bspwm/ ~/.config/     
mv sxhkd/ ~/.config/     
mv polybar/ ~/.config/ 
mv dunst/ ~/.config/     
mv rofi/ ~/.config/
mv nvim/ ~/.config/
mv vim/ ~/.config/

mkdir --parents /usr/share/xfce4/terminal/colorschemes/; mv xfce4TerminalColorSchemes/* $_

mv user-dirs.dirs ~/.config

mv .bashrc ~/
mv .profile ~/
mv .wallpaper/ ~/
